services:
  explorer-backend:
    profiles: [explorer]
    image: gatewayfm/midenscan-backend:v0.8.5
    pull_policy: missing
    environment:
      DB_CONN: postgres://midenscan:midenscan@explorer-database:5432/midenscan?sslmode=disable
      APP_ENVIRONMENT: development
      SERVER_PLAYGROUND_ENABLED: "true"
      SERVER_READ_TIMEOUT: 15s
      SERVER_WRITE_TIMEOUT: 15s
      SERVER_IDLE_TIMEOUT: 60s
      SERVER_GRAPHQL_QUERY_CACHE_SIZE: "1000"
      CORS_ALLOWED_ORIGINS: http://localhost:8080,http://127.0.0.1:8080
      METRICS_ADDRESS: ":8200"
      METRICS_NAMESPACE: midenscan
      METRICS_SUBSYSTEM: api
      METRICS_SCRAPE_INTERVAL: 15s
      LOG_LEVEL: debug
      LOG_ADD_SOURCE: "false"
      GRACE_TIMEOUT: 15s
      NETWORK_STATUS_URL: https://status.devnet.miden.io/status
      NETWORK_STATUS_DASHBOARD_URL: https://status.devnet.miden.io
      VERIFIED_COMPONENTS_URL: https://miden-playground-api.walnut.dev/verified-account-components/mdev
      VERIFIED_COMPONENTS_TIMEOUT: 10s
      VERIFIED_NOTES_URL: https://miden-playground-api.walnut.dev/verified-notes/mdev
      VERIFIED_NOTES_TIMEOUT: 10s
    ports:
      - "127.0.0.1:8199:8199"
    depends_on:
      explorer-database:
        condition: service_healthy
      explorer-migration:
        condition: service_completed_successfully
    restart: unless-stopped
