[package]
name = "miden-rpc-proto"
version = "0.3.0"
description = "Miden node RPC message definitions"
readme = "README.md"
keywords = ["miden", "node", "protobuf", "rpc"]
categories = ["no-std"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = ["std"]
std = []

[dependencies]
prost = { version = "0.12" }
