version = 1
timestamp = 1717344256

[[faucet]]
symbol = "MID"
decimals = 12
max_supply = 1000000
storage_mode = "public"
fungible = true

[[account]]
mutable = false
storage_mode = "private"
assets = [
    { symbol = "MID", amount = 1000 }
]
