[workspace]
changelog_update = false # For now we have our own changelog.
release_always   = true  # Without the tracking PR, it would never trigger unless `true`.

git_release_enable = false
git_tag_enable     = false
