[workspace]
members = [
    "proto",
    "rpc",
    "store",
    "tx_pipeline",
    "utils",
]
resolver = "2"

[workspace.dependencies]
miden-crypto = { git = "https://github.com/0xPolygonMiden/crypto", branch = "next", default-features = false, features = ["std"] }
miden_objects = { package = "miden-objects", git = "https://github.com/0xPolygonMiden/miden-base.git", branch = "main", default-features = false }
