[workspace]
members = [
    "block-producer",
    "proto",
    "rpc",
    "store",
    "utils",
]
resolver = "2"

[workspace.dependencies]
miden-crypto = { package = "miden-crypto", git = "https://github.com/0xPolygonMiden/crypto.git", branch = "next", features = ["std"] }
miden_objects = { package = "miden-objects", git = "https://github.com/0xPolygonMiden/miden-base.git", branch = "main", default-features = false }
thiserror = "1.0"
