[workspace]
members = [
  "bin/node",
  "crates/faucet",
  "crates/block-producer",
  "crates/proto",
  "crates/rpc",
  "crates/store",
  "crates/utils",
  "crates/test-macro",
]
default-members = ["bin/node"]

resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.77"
license = "MIT"
authors = ["Miden contributors"]
readme = "README.md"
homepage = "https://polygon.technology/polygon-miden"
repository = "https://github.com/0xPolygonMiden/miden-node"
exclude = [".github/"]

[workspace.dependencies]
miden-air = { version = "0.9", default-features = false }
miden-lib = { git = "https://github.com/0xPolygonMiden/miden-base", branch = "polydez-refactor-account-update" }
miden-node-block-producer = { path = "crates/block-producer" }
miden-node-faucet = { path = "crates/faucet" }
miden-node-proto = { path = "crates/proto" }
miden-node-rpc = { path = "crates/rpc" }
miden-node-store = { path = "crates/store" }
miden-node-test-macro = { path = "crates/test-macro" }
miden-node-utils = { path = "crates/utils" }
miden-objects = { git = "https://github.com/0xPolygonMiden/miden-base", branch = "polydez-refactor-account-update" }
miden-processor = { version = "0.9" }
miden-stdlib = { version = "0.9", default-features = false }
miden-tx = { git = "https://github.com/0xPolygonMiden/miden-base", branch = "polydez-refactor-account-update" }
thiserror = { version = "1.0" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = [
  "fmt",
  "json",
  "env-filter",
] }
