[workspace]
members = [
  "block-producer",
  "node",
  "proto",
  "rpc",
  "store",
  "utils",
  "test-macro",
  "faucet"
]

resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.75"
license = "MIT"
authors = ["Miden contributors"]
readme = "README.md"
homepage = "https://polygon.technology/polygon-miden"
repository = "https://github.com/0xPolygonMiden/miden-node"
exclude = [".github/"]

[workspace.dependencies]
miden-air = { git = "https://github.com/0xPolygonMiden/miden-vm.git", branch = "polydez-minimal-error-traits", default-features = false }
miden-lib = { git = "https://github.com/0xPolygonMiden/miden-base.git", branch = "polydez-minimal-error-traits" }
miden-objects = { git = "https://github.com/0xPolygonMiden/miden-base.git", branch = "polydez-minimal-error-traits" }
miden-processor = { git = "https://github.com/0xPolygonMiden/miden-vm.git", branch = "polydez-minimal-error-traits" }
miden-stdlib = { git = "https://github.com/0xPolygonMiden/miden-vm.git", branch = "polydez-minimal-error-traits", default-features = false }
miden-tx = { git = "https://github.com/0xPolygonMiden/miden-base.git", branch = "polydez-minimal-error-traits" }
thiserror = { version = "1.0" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = [
  "fmt",
  "json",
  "env-filter",
] }
