[workspace]
members = [
  "block-producer",
  "node",
  "proto",
  "rpc",
  "store",
  "utils",
  "test-macro",
]
resolver = "2"

[workspace.dependencies]
miden-air = { version = "0.8", default-features = false }
miden-lib = { version = "0.1" }
miden-objects = { version = "0.1" }
miden-processor = { version = "0.8" }
miden-stdlib = { version = "0.8", default-features = false }
miden-tx = { version = "0.1" }
miden-vm = { version = "0.8", default-features = false }
thiserror = { version = "1.0" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = [
  "fmt",
  "json",
  "env-filter",
] }
