[workspace]
members = [
  "bin/node",
  "bin/faucet",
  "crates/block-producer",
  "crates/proto",
  "crates/rpc-proto",
  "crates/rpc",
  "crates/store",
  "crates/utils",
  "crates/test-macro",
]
default-members = ["bin/faucet", "bin/node", "crates/proto", "crates/rpc-proto"]

resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.78"
license = "MIT"
authors = ["Miden contributors"]
homepage = "https://polygon.technology/polygon-miden"
repository = "https://github.com/0xPolygonMiden/miden-node"
exclude = [".github/"]
readme = "README.md"

[workspace.dependencies]
miden-air = { version = "0.9", default-features = false }
miden-lib = { version = "0.4" }
miden-node-block-producer = { path = "crates/block-producer", version = "0.4" }
miden-node-faucet = { path = "bin/faucet", version = "0.4" }
miden-node-proto = { path = "crates/proto", version = "0.4" }
miden-node-rpc = { path = "crates/rpc", version = "0.4" }
miden-node-rpc-proto = { path = "crates/rpc-proto", version = "0.4" }
miden-node-store = { path = "crates/store", version = "0.4" }
miden-node-test-macro = { path = "crates/test-macro" }
miden-node-utils = { path = "crates/utils", version = "0.4" }
miden-objects = { version = "0.4" }
miden-processor = { version = "0.9" }
miden-stdlib = { version = "0.9", default-features = false }
miden-tx = { version = "0.4" }
thiserror = { version = "1.0" }
tonic = { version = "0.11" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["fmt",  "json",  "env-filter"] }
