# Cargo Makefile

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy-default]
command = "cargo"
args = ["clippy","--workspace", "--all-targets", "--", "-D", "clippy::all", "-D", "warnings"]

[tasks.clippy-all-features]
command = "cargo"
args = ["clippy","--workspace", "--all-targets", "--all-features", "--", "-D", "clippy::all", "-D", "warnings"]

[tasks.clippy]
dependencies = [
  "clippy-default",
  "clippy-all-features"
]

[tasks.doc]
command = "cargo"
args = ["doc", "--all-features", "--release"]

[tasks.test]
command = "cargo"
args = ["test", "--all-features", "--workspace", "--", "--nocapture"]

[tasks.lint]
dependencies = [
    "format",
    "clippy",
    "doc"
]
