# Cargo Makefile

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy-default]
toolchain = "nightly"
command = "cargo"
args = ["clippy","--workspace", "--all-targets", "--", "-D", "clippy::all", "-D", "warnings"]

[tasks.clippy-all-features]
toolchain = "nightly"
command = "cargo"
args = ["clippy","--workspace", "--all-targets", "-all-features", "--", "-D", "clippy::all", "-D", "warnings"]

[tasks.clippy]
toolchain = "nightly"
dependencies = [
  "clippy-default",
  "clippy-all-features"
]

[tasks.prepare]
toolchain = "nightly"
dependencies = [
    "format",
    "clippy",
]
