# Cargo Makefile

# If running cargo-make in a workspace you need to add this env variable to make sure it function correctly.
# See docs: https://github.com/sagiegurari/cargo-make?tab=readme-ov-file#usage
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

# linting
[tasks.format]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all"]

[tasks.format-check]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy-default]
command = "cargo"
args = ["clippy","--workspace", "--all-targets", "--", "-D", "clippy::all", "-D", "warnings"]

[tasks.clippy-all-features]
command = "cargo"
args = ["clippy","--workspace", "--all-targets", "--all-features", "--", "-D", "clippy::all", "-D", "warnings"]

[tasks.clippy]
dependencies = [
  "clippy-default",
  "clippy-all-features"
]

[tasks.doc]
env = { "RUSTDOCFLAGS" = "-D warnings" }
command = "cargo"
args = ["doc", "--verbose", "--all-features", "--keep-going", "--release"]

[tasks.lint]
dependencies = [
    "format",
    "format-check",
    "clippy",
    "docs"
]

# testing
[tasks.test]
command = "cargo"
args = ["test", "--all-features", "--workspace", "--", "--nocapture"]

[tasks.test-end-to-end]
workspace = false
script = '''
cargo install --features testing --path node

miden-node make-genesis --inputs-path node/genesis.toml --force

miden-node start --config node/miden-node.toml &

sleep 10

./scripts/test-end-to-end.sh

pkill -f miden-node
'''

# docker
[tasks.docker-build-node]
workspace = false
script = '''
CREATED=$(date)
VERSION=$(cat node/Cargo.toml | grep -m 1 '^version' | cut -d '"' -f 2)
COMMIT=$(git rev-parse HEAD)

docker build --build-arg CREATED="$CREATED" \
             --build-arg VERSION="$VERSION" \
             --build-arg COMMIT="$COMMIT" \
             -f node/Dockerfile \
             -t miden-node-image .
'''

[tasks.docker-run-node]
workspace = false
script = '''
docker volume create miden-db

ABSOLUTE_PATH="$(pwd)/node/miden-node.toml"

docker run --name miden-node \
           -p 57291:57291 \
           -v miden-db:/db \
           -v "${ABSOLUTE_PATH}:/miden-node.toml" \
           -d miden-node-image
'''
