# Cargo Makefile

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clippy]
toolchain = "nightly"
command = "cargo"
args = ["clippy"]

[tasks.docker-build-node]
command = "docker"
args = ["build", "-f", "node/Dockerfile", "-t", "miden-node-image", "."]
workspace = false

[tasks.prepare]
toolchain = "nightly"
dependencies = [
    "format",
    "clippy",
]
