array_width = 80
attr_fn_like_width = 80
chain_width = 80
edition = "2021"
fn_call_width = 80
fn_params_layout = "Vertical"
match_block_trailing_comma = true
newline_style = "Unix"
single_line_if_else_max_width = 60
use_field_init_shorthand = true
use_try_shorthand = true
