name: build-package
description: Builds miden-node and miden-faucet debian packages for the given git reference
inputs:
  gitref:
    required: true
    description: The git ref to build the packages from.

runs:
  using: "composite"
  steps:
    - name: Identify target git SHA
      id: git-sha
      shell: bash
      run: |
        if git show-ref -q --verify "refs/remotes/origin/$gitref" 2>/dev/null; then
          echo "sha=$(git show-ref --hash --verify "refs/remotes/origin/$gitref")" >> $GITHUB_OUTPUT
        elif git show-ref -q --verify "refs/tags/$gitref" 2>/dev/null; then
          echo "sha=$(git show-ref --hash --verify "refs/tags/$gitref")" >> $GITHUB_OUTPUT
        elif git rev-parse --verify "$gitref^{commit}" >/dev/null 2>&1; then
          echo "sha=$(git rev-parse --verify "$gitref^{commit})" >> $GITHUB_OUTPUT
        else
          echo "::error Unknown git reference type"
          # exit 1
        fi

    - name: Build binaries
      run: |
        cargo install miden-node   --locked --features testing --git ${{ github.repositoryUrl }} --rev ${{ steps.git-sha.outputs.sha }}
        cargo install miden-faucet --locked --features testing --git ${{ github.repositoryUrl }} --rev ${{ steps.git-sha.outputs.sha }}
    
    - name: Create package directories
      run: |
        mkdir -p \
          packaging/deb/miden-node/DEBIAN \
          packaging/deb/miden-node/usr/bin\
          packaging/deb/miden-node/lib/systemd/system\
          packaging/deb/miden-node/etc/miden\
          packaging/deb/miden-node/opt/miden/miden-faucet

        mkdir -p \
          packaging/deb/miden-faucet/DEBIAN \
          packaging/deb/miden-faucet/usr/bin\
          packaging/deb/miden-faucet/lib/systemd/system\
          packaging/deb/miden-faucet/etc/miden\
          packaging/deb/miden-faucet/opt/miden/miden-faucet

    - name: Copy binary files
      run: |
        cp -p $CARGO_HOME/bin/miden-node   packaging/deb/miden-node/urs/bin/
        cp -p $CARGO_HOME/bin/miden-faucet packaging/deb/miden-faucet/urs/bin/

    # These have to be downloaded as the current repo source isn't necessarily the target git reference.
    - name: Copy package install scripts
      run: |
        git show ${{ steps.git-sha.outputs.sha }}:packaging/miden-node.service   > packaging/deb/miden-node/lib/systemd/system/miden-node.service
        git show ${{ steps.git-sha.outputs.sha }}:packaging/postinst             > packaging/deb/miden-node/DEBIAN/postinst
        git show ${{ steps.git-sha.outputs.sha }}:packaging/postrm               > packaging/deb/miden-node/DEBIAN/postrm
        git show ${{ steps.git-sha.outputs.sha }}:packaging/miden-faucet.service > packaging/deb/miden-faucet/lib/systemd/system/miden-faucet.service
        git show ${{ steps.git-sha.outputs.sha }}:packaging/postinst             > packaging/deb/miden-faucet/DEBIAN/postinst
        git show ${{ steps.git-sha.outputs.sha }}:packaging/postrm               > packaging/deb/miden-faucet/DEBIAN/postrm

    - name: Create control files
      run: |
        cat > packaging/deb/miden-node/DEBIAN/control << EOF
        Package: miden-node
        Version: ${{ inputs.gitref }} 
        Section: base
        Priority: optional
        Architecture: $(uname -m)
        Maintainer: Polygon Devops <devops@polygon.technology>
        Description: miden-node binary package
        Homepage: https://polygon.technology/polygon-miden
        Vcs-Git: git@github.com:0xPolygonMiden/miden-node.git
        Vcs-Browser: https://github.com/0xPolygonMiden/miden-node
        EOF

        cat > packaging/deb/miden-faucet/DEBIAN/control << EOF
        Package: miden-faucet
        Version: ${{ inputs.gitref }} 
        Section: base
        Priority: optional
        Architecture: $(uname -m)
        Maintainer: Polygon Devops <devops@polygon.technology>
        Description: miden-faucet binary package
        Homepage: https://polygon.technology/polygon-miden
        Vcs-Git: git@github.com:0xPolygonMiden/miden-node.git
        Vcs-Browser: https://github.com/0xPolygonMiden/miden-node
        EOF

    - name: Build packages
      run: |
        dpkg-deb --build --root-owner-group packaging/deb/miden-node
        dpkg-deb --build --root-owner-group packaging/deb/miden-faucet
