[package]
name = "miden-node-stress-test"
description = "A binary for running stress tests against the Miden node"
keywords = ["miden", "stress-test"]
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
readme.workspace = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "string"] }
miden-lib = { workspace = true }
miden-node-block-producer = { workspace = true, features = ["testing"]}
miden-node-proto = { workspace = true }
miden-node-store = { workspace = true }
miden-objects = { workspace = true, features = ["testing"] }
miden-processor = { workspace = true }
rand = { version = "0.8" }
rayon = "1.10"
tokio = { workspace = true, features = ["rt-multi-thread", "net", "macros", "sync", "time"] }
