[package]
authors.workspace      = true
description            = "A binary for running stress tests against the Miden node"
edition.workspace      = true
exclude.workspace      = true
homepage.workspace     = true
keywords               = ["miden", "stress-test"]
license.workspace      = true
name                   = "miden-node-stress-test"
readme.workspace       = true
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive", "string"] }
miden-block-prover = { git = "https://github.com/0xPolygonMiden/miden-base.git", branch = "next", features = [
  "testing",
] }
miden-lib = { workspace = true }
miden-node-block-producer = { workspace = true, features = ["testing"] }
miden-node-proto = { workspace = true }
miden-node-store = { workspace = true }
miden-node-utils = { workspace = true }
miden-objects = { workspace = true, features = ["testing"] }
miden-processor = { workspace = true }
rand = { version = "0.8" }
rayon = "1.10"
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tonic = { workspace = true }
