[package]
name = "miden-faucet"
version.workspace = true
description = "Miden node token faucet"
readme = "README.md"
keywords = ["miden", "node", "faucet"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
# Makes `make-genesis` subcommand run faster. Is only suitable for testing.
# INFO: Make sure that all your components have matching features for them to function.
testing = ["miden-objects/testing", "miden-lib/testing"]

[dependencies]
actix-cors = "0.7"
actix-web = "4.8"
actix-web-static-files = "4.0"
async-mutex = "1.4"
clap = { version = "4.5", features = ["derive"] }
derive_more = "0.99"
figment = { version = "0.10", features = ["toml", "env"] }
miden-lib = { workspace = true, features = ["concurrent"] }
miden-node-proto = { workspace = true }
miden-node-utils = { workspace = true }
miden-objects = { workspace = true , features = ["concurrent"] }
miden-tx = { workspace = true,  features = ["concurrent"] }
rand = { version = "0.8" }
rand_chacha = "0.3"
serde = { version = "1.0", features = ["derive"] }
static-files = "0.2.1"
thiserror = { workspace = true }
toml = { version = "0.8" }
tonic = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
static-files = "0.2.1"
