[package]
authors.workspace      = true
description            = "Miden node token faucet"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["faucet", "miden", "node"]
license.workspace      = true
name                   = "miden-faucet"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version                = "0.9.0"

[lints]
workspace = true

[dependencies]
anyhow                       = { workspace = true }
async-trait                  = "0.1"
axum                         = { features = ["tokio"], version = "0.8" }
axum-extra                   = { version = "0.10" }
base64                       = "0.21"
clap                         = { features = ["derive", "env", "string"], version = "4.5" }
http                         = { workspace = true }
miden-lib                    = { workspace = true }
miden-node-proto             = { workspace = true }
miden-node-rpc               = { workspace = true }
miden-node-utils             = { workspace = true }
miden-objects                = { workspace = true }
miden-proving-service-client = { features = ["tx-prover"], version = "0.9" }
miden-tx                     = { features = ["concurrent"], workspace = true }
rand                         = { features = ["thread_rng"], workspace = true }
rand_chacha                  = "0.9"
serde                        = { features = ["derive"], version = "1.0" }
serde_json                   = { version = "1.0" }
sha3                         = { version = "0.10" }
thiserror                    = { workspace = true }
tokio                        = { features = ["fs"], workspace = true }
tokio-stream                 = { features = ["net"], workspace = true }
toml                         = { version = "0.8" }
tonic                        = { features = ["tls-native-roots"], workspace = true }
tower                        = { workspace = true }
tower-http                   = { features = ["cors", "set-header", "trace"], workspace = true }
tower_governor               = "0.7.0"
tracing                      = { workspace = true }
url                          = { workspace = true }
winter-maybe-async           = { version = "0.12" }

[build-dependencies]
# Required to inject build metadata.
miden-node-utils = { features = ["vergen"], workspace = true }

[dev-dependencies]
fantoccini                = { version = "0.21" }
miden-node-block-producer = { features = ["testing"], workspace = true }
miden-objects             = { features = ["testing"], workspace = true }
serde_json                = { version = "1.0" }
tokio-stream              = { features = ["net"], workspace = true }
tonic-web                 = { version = "0.12" }

# Required to avoid false positives in cargo-machete
# This is due to the `winter-maybe-async` crate not working standalone.
[package.metadata.cargo-machete]
ignored = ["async-trait"]
