[package]
name = "miden-faucet"
version = "0.3.1"
description = "Miden node token faucet"
readme = "README.md"
keywords = ["miden", "node", "faucet"]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
# Makes `make-genesis` subcommand run faster. Is only suitable for testing.
# INFO: Make sure that all your components have matching features for them to function.
testing = ["miden-objects/testing", "miden-lib/testing"]

[dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.5"
actix-web = "4"
async-mutex = "1.4.0"
derive_more = "0.99.17"
figment = { version = "0.10", features = ["toml", "env"] }
miden-lib = { package = "miden-lib", git = "https://github.com/0xPolygonMiden/miden-base.git", branch = "next" }
miden-node-proto = { workspace = true }
miden-node-utils = { workspace = true }
miden-objects = { package = "miden-objects", git = "https://github.com/0xPolygonMiden/miden-base.git", branch = "next" }
miden-tx = { package = "miden-tx", git = "https://github.com/0xPolygonMiden/miden-base.git", branch = "next",  features = ["concurrent"] }
tonic = { version = "0.11" }
rand_chacha = "0.3"
rand = { version = "0.8.5" }
serde = { version = "1.0", features = ["derive"] }
tracing = { workspace = true }
thiserror = { workspace = true }
