# This action should deploy the given node and faucet packages to the provided aws instance using ssm and scp.

name: 'Deploy node and faucet'
description: 'Deploys the node and faucet Debian packages to an aws instance.'
inputs:
  role-to-assume:
    required: true
  aws-region:
    required: true
  instance-id:
    required: true
  node-package:
    required: true
  faucet-package:
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: GithubActionsSession

    - name: Rest of the owl
      run: echo "The rest of the stuff should be copy pasted in, but use the **-package filepaths to scm the packages across."
