timestamp = 1717344256
version   = 1

[[faucet]]
decimals     = 12
max_supply   = 1000000
storage_mode = "public"
symbol       = "MIDEN"
# fungible = true # default value

[[wallet]]
assets       = [{ amount = 999, symbol = "MIDEN" }]
mutable      = false
storage_mode = "private"
# has_updatable_code = false # default value
