[package]
authors.workspace      = true
description            = "Miden node binary"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["miden", "node"]
license.workspace      = true
name                   = "miden-node"
readme.workspace       = true
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[features]
tracing-forest = ["miden-node-block-producer/tracing-forest"]

[dependencies]
anyhow                    = { workspace = true }
clap                      = { features = ["derive", "env", "string"], version = "4.5" }
fs-err                    = { workspace = true }
humantime                 = { workspace = true }
miden-lib                 = { workspace = true }
miden-node-block-producer = { workspace = true }
miden-node-ntx-builder    = { workspace = true }
miden-node-rpc            = { workspace = true }
miden-node-store          = { workspace = true }
miden-node-utils          = { workspace = true }
miden-objects             = { workspace = true }
rand                      = { workspace = true }
rand_chacha               = { version = "0.9" }
tokio                     = { features = ["macros", "net", "rt-multi-thread"], workspace = true }
url                       = { workspace = true }

[dev-dependencies]
figment          = { features = ["env", "test", "toml"], version = "0.10" }
miden-node-utils = { features = ["tracing-forest"], workspace = true }

[build-dependencies]
# Required to inject build metadata.
miden-node-utils = { features = ["vergen"], workspace = true }
