# This is an example genesis input file for the Miden node.
timestamp = 1672531200
version   = 1

[[accounts]]
auth_scheme  = "RpoFalcon512"
decimals     = 12
max_supply   = 1000000
storage_mode = "public"
token_symbol = "POL"
type         = "BasicFungibleFaucet"
