# This is an example genesis input file for the Miden node.
version = 1
timestamp = 1672531200

[[accounts]]
type = "BasicFungibleFaucet"
storage_mode = "public"
auth_scheme = "RpoFalcon512"
token_symbol = "POL"
decimals = 12
max_supply = 1000000
