endpoint = { host = "localhost",  port = 8080 }
database_filepath = "store.sqlite3"
node_url = "http://localhost:57291"
timeout_ms = 10000

# Data used to construct the faucet account of the faucet
asset_amount_options = [100, 500, 1000]
token_symbol = "POL"
decimals = 8
max_supply = 1000000
