# This is an example configuration file for the Miden node.

[block_producer]
# port defined as: sum(ord(c)**p for (p, c) in enumerate('miden-block-producer', 1)) % 2**16
endpoint = "http://127.0.0.1:48046"
# enables or disables the verification of transaction proofs before they are accepted into the
# transaction queue.
verify_tx_proofs = true
# address of the remote batch prover service
batch_prover_url = "http://127.0.0.1:8081/"
# address of the remote block prover service
block_prover_url = "http://127.0.0.1:8082/"

[rpc]
# port defined as: sum(ord(c)**p for (p, c) in enumerate('miden-rpc', 1)) % 2**16
endpoint = "http://0.0.0.0:57291"

[store]
# port defined as: sum(ord(c)**p for (p, c) in enumerate('miden-store', 1)) % 2**16
blockstore_dir    = "/opt/miden/blocks"
database_filepath = "/opt/miden/miden-store.sqlite3"
endpoint          = "http://127.0.0.1:28943"
genesis_filepath  = "/opt/miden/genesis.dat"
