services:
  sequencer:
    image: ${MIDEN_NODE_IMAGE:-miden-node}
    pull_policy: if_not_present
    volumes:
      - node-data:/data
    depends_on:
      bootstrap-node:
        condition: service_completed_successfully
      otel-collector:
        condition: service_started
      validator:
        condition: service_started
    command:
      - miden-node
      - sequencer
      - --rpc.listen=0.0.0.0:57291
      - --data-directory=/data/node
      - --validator.url=http://validator:50101
      - --ntx-builder.url=http://ntx-builder:50301
      - --rpc.network-tx-auth-header-value=secret_value
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_RESOURCE_ATTRIBUTES: service.instance.id=sequencer
    ports:
      - "127.0.0.1:57291:57291"
