[package]
name = "miden-node-proto"
version = "0.1.0"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-node"
keywords = ["miden", "node", "program", "proto"]
edition = "2021"
rust-version = "1.73"

[dependencies]
hex = { version = "0.4" }
miden-crypto = { workspace = true }
miden-block-producer = { path = "../block-producer", version = "0.1"}
miden_objects = { workspace = true }
prost = { version = "0.12" }
tonic = { version = "0.10" }

[dev-dependencies]
proptest = { version = "1.2" }

[build-dependencies]
miette = { version = "5.9", features = ["fancy"] }
prost = { version = "0.12" }
protox = { version = "0.5" }
tonic-build = { version = "0.10" }
