[block_producer]
store_url = "http://localhost:28943"
# port defined as: sum(ord(c)**p for (p, c) in enumerate('miden-block-producer', 1)) % 2**16
endpoint = { host = "localhost", port = 48046 }

[rpc]
store_url = "http://localhost:28943"
block_producer_url = "http://localhost:48046"
# port defined as: sum(ord(c)**p for (p, c) in enumerate('miden-rpc', 1)) % 2**16
endpoint = { host = "localhost", port = 57291 }

[store]
database_filepath = "miden-store.sqlite3"
genesis_filepath = "genesis.dat"
# port defined as: sum(ord(c)**p for (p, c) in enumerate('miden-store', 1)) % 2**16
endpoint = { host = "localhost", port = 28943 }
