[package]
name = "miden-node-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0" }
figment = { version = "0.10", features = ["toml", "env"] }
miden-node-proto = { path = "../proto" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.29" }
tonic = { version = "0.10" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
