[package]
name = "miden-node-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
figment = { version = "0.10", features = ["toml", "env"] }
directories = { version = "5.0" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" , features = ["fmt"] }
anyhow = { version = "1.0" }
serde = { version = "1.0" , features = ["derive"] }
