[package]
name = "miden-node-utils"
version = "0.1.0"
edition = "2021"

[features]
testing = ["miden-lib/testing"]

[dependencies]
anyhow = { version = "1.0" }
clap = { version = "4.4.11", features = ["derive"] }
directories = { version = "5.0" }
figment = { version = "0.10", features = ["toml", "env"] }
miden-crypto = { workspace = true }
miden-lib = { workspace = true, features = ["concurrent"] }
miden_objects = { workspace = true, features = ["serde"] }
once_cell = { version = "1.18.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
