[package]
name = "miden-node-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0" }
figment = { version = "0.10", features = ["toml", "env"] }
hex = { version = "0.4" }
serde = { version = "1.0", features = ["derive"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
