[package]
authors.workspace      = true
description            = "Miden blockchain proving service"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["miden", "proving", "service"]
license.workspace      = true
name                   = "miden-proving-service"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version                = "0.10.0"

[[bin]]
name = "miden-proving-service"
path = "src/main.rs"

[features]
concurrent = ["miden-tx/concurrent"]
default    = ["concurrent"]

[lints]
workspace = true

[dependencies]
async-trait                        = { version = "0.1" }
axum                               = { version = "0.8" }
bytes                              = { version = "1.0" }
clap                               = { version = "4.5", features = ["derive", "env"] }
miden-block-prover                 = { workspace = true }
miden-lib                          = { workspace = true }
miden-objects                      = { workspace = true, features = ["std"] }
miden-tx                           = { workspace = true, features = ["std"] }
miden-tx-batch-prover              = { workspace = true, features = ["std"] }
opentelemetry                      = { version = "0.29", features = ["metrics", "trace"] }
opentelemetry-otlp                 = { version = "0.29", features = ["grpc-tonic"] }
opentelemetry-semantic-conventions = { version = "0.29" }
opentelemetry_sdk                  = { version = "0.29", features = ["metrics", "rt-tokio"] }
pingora                            = { version = "0.5", features = ["lb"] }
pingora-core                       = { version = "0.5" }
pingora-limits                     = { version = "0.5" }
pingora-proxy                      = { version = "0.5" }
prometheus                         = { version = "0.14" }
prost                              = { version = "0.13", default-features = false, features = ["derive"] }
reqwest                            = { version = "0.12" }
serde                              = { version = "1.0", features = ["derive"] }
serde_json                         = { version = "1.0" }
serde_qs                           = { version = "0.15" }
thiserror                          = { workspace = true }
tokio                              = { version = "1.44", features = ["full"] }
tokio-stream                       = { version = "0.1", features = ["net"] }
tonic                              = { version = "0.12", default-features = false, features = ["codegen", "prost", "transport"] }
tonic-health                       = { version = "0.12" }
tonic-web                          = { version = "0.12" }
tracing                            = { version = "0.1" }
tracing-opentelemetry              = { version = "0.30" }
tracing-subscriber                 = { version = "0.3", features = ["env-filter", "fmt", "json"] }
uuid                               = { version = "1.16", features = ["v4"] }

[dev-dependencies]
miden-lib     = { workspace = true, features = ["testing"] }
miden-objects = { workspace = true, features = ["testing"] }
miden-testing = { workspace = true }
miden-tx      = { workspace = true, features = ["testing"] }

[build-dependencies]
miette      = { version = "7.5", features = ["fancy"] }
prost       = { version = "0.13", default-features = false, features = ["derive"] }
prost-build = { version = "0.13" }
protox      = { version = "0.8" }
tonic-build = { version = "0.12" }
