[package]
authors.workspace      = true
description            = "Miden node's state store component"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["miden", "node", "store"]
license.workspace      = true
name                   = "miden-node-store"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
anyhow             = { workspace = true }
deadpool           = { default-features = false, features = ["managed", "rt_tokio_1"], version = "0.12" }
deadpool-sync      = { version = "0.1" }
hex                = { version = "0.4" }
miden-core         = { branch = "tomasarrachea-notes-migration", git = "https://github.com/lambdaclass/miden-vm/" }
miden-lib          = { workspace = true }
miden-node-proto   = { workspace = true }
miden-node-utils   = { workspace = true }
miden-objects      = { workspace = true }
rusqlite           = { features = ["array", "buildtime_bindgen", "bundled"], version = "0.35" }
rusqlite_migration = { version = "2.1" }
thiserror          = { workspace = true }
tokio              = { features = ["fs", "macros", "net", "rt-multi-thread"], workspace = true }
tokio-stream       = { features = ["net"], workspace = true }
tonic              = { workspace = true }
tower-http         = { features = ["util"], workspace = true }
tracing            = { workspace = true }
rayon              = { version = "1.10" }
serde_json         = { version = "1.0" }

[dev-dependencies]
assert_matches        = { workspace = true }
miden-lib             = { features = ["testing"], workspace = true }
miden-node-test-macro = { workspace = true }
miden-node-utils      = { features = ["tracing-forest"], workspace = true }
miden-objects         = { features = ["testing"], workspace = true }
rand                  = { version = "0.9" }
regex                 = { version = "1.11" }
termtree              = { version = "0.5" }
