[book]
title = "The Miden Node"
authors = ["Miden team"]
description = "Manual for the software which processes transactions and creates blocks for the Miden rollup"
multilingual = false
language = "en"

[output.html]
git-repository-url = "https://github.com/0xPolygonMiden/miden-node"

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[output.linkcheck]
