[book]
authors      = ["Miden contributors"]
description  = "Operator and developer manual for the software which is responsible for aggregating transactions into blocks for the Miden blockchain."
language     = "en"
multilingual = false
title        = "The Miden node"

[output.html]
git-repository-url = "https://github.com/0xPolygonMiden/miden-node"

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[output.linkcheck]
