syntax = "proto3";
package vm;

import "types/primitives.proto";

enum ExecutionProofHashFunction {
    EXECUTION_PROOF_HASH_FUNCTION_UNSPECIFIED = 0;
    EXECUTION_PROOF_HASH_FUNCTION_BLAKE3_256 = 1;
    EXECUTION_PROOF_HASH_FUNCTION_RPO_256 = 2;
    EXECUTION_PROOF_HASH_FUNCTION_RPX_256 = 3;
    EXECUTION_PROOF_HASH_FUNCTION_POSEIDON2 = 4;
    EXECUTION_PROOF_HASH_FUNCTION_KECCAK = 5;
}

message StarkProof {
    bytes proof = 1;
    ExecutionProofHashFunction hash_function = 2;
}

message DeferredDataChunk {
    // Exactly eight canonical field elements.
    repeated primitives.Felt elements = 1;
}

message DeferredData {
    repeated DeferredDataChunk chunks = 1;
}

message DeferredJoin {
    fixed32 lhs = 1;
    fixed32 rhs = 2;
}

message DeferredIndexPair {
    fixed32 lhs = 1;
    fixed32 rhs = 2;
}

message DeferredPairList {
    repeated DeferredIndexPair pairs = 1;
}

message DeferredWireEntry {
    primitives.Word tag = 1;

    oneof entry {
        DeferredData data = 2;
        DeferredJoin join = 3;
        DeferredPairList pair_list = 4;
    }
}

message DeferredStateWire {
    repeated DeferredWireEntry entries = 1;
}

message EmptyDeferredProof {}

message DeferredStarkProof {
    StarkProof proof = 1;
    primitives.Word public_root = 2;
}

message DeferredProof {
    oneof proof {
        EmptyDeferredProof empty = 1;
        DeferredStateWire wire = 2;
        DeferredStarkProof stark = 3;
    }
}

message ExecutionProof {
    StarkProof miden = 1;
    DeferredProof deferred = 2;
}
