name: amd_deb_packager

on:
  release:
    types: [released, prereleased]

jobs:
  build:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      ##### TAG Variable #####
      - name: Adding TAG to ENV
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: adding version
        run: |
          NUMERIC_VERSION=$( echo ${{ env.GIT_TAG }} | sed 's/[^0-9.]//g' )
          echo "VERSION=$NUMERIC_VERSION" >> $GITHUB_ENV

      - name: cleaning repo
        run: cargo clean

      - name: Building for amd64
        run: cargo build --release

      - name: create package directories
        run: |
          mkdir -p packaging/deb/miden-node/DEBIAN
          mkdir -p packaging/deb/miden-node/usr/bin
          mkdir -p packaging/deb/miden-node/lib/systemd/system
          mkdir -p packaging/deb/miden-node/etc/miden

      - name: copy package files
        run: |
          cp -p target/release/miden-node packaging/deb/miden-node/usr/bin/
          cp config/miden-node.toml packaging/deb/miden-node/etc/miden/
          cp config/genesis.toml packaging/deb/miden-node/etc/miden/
          cp packaging/miden-node.service packaging/deb/miden-node/lib/systemd/system/
          cp packaging/postinst packaging/deb/miden-node/DEBIAN/postinst
          cp packaging/postrm packaging/deb/miden-node/DEBIAN/postrm

      ########### Control file creation for amd64 ##########
      - name: create control file
        run: |
          touch packaging/deb/miden-node/DEBIAN/control
          echo "Package: miden-node" >> packaging/deb/miden-node/DEBIAN/control
          echo "Version: ${{ env.VERSION }}" >> packaging/deb/miden-node/DEBIAN/control
          echo "Section: base" >> packaging/deb/miden-node/DEBIAN/control
          echo "Priority: optional" >> packaging/deb/miden-node/DEBIAN/control
          echo "Architecture: amd64" >> packaging/deb/miden-node/DEBIAN/control
          echo "Maintainer: Polygon Devops <devops@polygon.technology>" >> packaging/deb/miden-node/DEBIAN/control
          echo "Description: miden-node binary package" >> packaging/deb/miden-node/DEBIAN/control
          echo "Homepage: https://polygon.technology/polygon-miden" >> packaging/deb/miden-node/DEBIAN/control
          echo "Vcs-Git: git@github.com:0xPolygonMiden/miden-node.git" >> packaging/deb/miden-node/DEBIAN/control
          echo "Vcs-Browser: https://github.com/0xPolygonMiden/miden-node" >> packaging/deb/miden-node/DEBIAN/control

      - name: Creating package for binary for miden-node ${{ env.ARCH }}
        run: cp -rp packaging/deb/miden-node packaging/deb/miden-node-${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: amd64

      - name: Running package build
        run: dpkg-deb --build --root-owner-group packaging/deb/miden-node-${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: amd64

      - name: shasum the package
        run: cd packaging/deb/ && sha256sum miden-node-${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > miden-node-${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: amd64

      - name: release miden-node Packages
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.GIT_TAG }}
          prerelease: true
          files: |
            packaging/deb/miden-node**.deb
            packaging/deb/miden-node**.deb.checksum
