name: Docker Build Check

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]
    
permissions:
  contents: read

jobs:
  docker-build:
    strategy:
      matrix:
        component: [node, faucet]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker
        run: make docker-build-${{ matrix.component }}
