name: Docker Build Check

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  docker-build:
    strategy:
      matrix:
        component: [node, faucet]
    runs-on: ubuntu-latest
    name: Build ${{ matrix.component }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GithubActionsSession

      - name: Set cache key
        id: cache-key
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "cache_key=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
          else
            echo "cache_key=main" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          cache-binary: true

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          file: ./bin/${{ matrix.component }}/Dockerfile
          cache-from: type=s3,region=${{ secrets.AWS_REGION }},bucket=${{ secrets.AWS_CACHE_BUCKET }},name=miden-node-${{ steps.cache-key.outputs.cache_key }}
          cache-to: type=s3,region=${{ secrets.AWS_REGION }},bucket=${{ secrets.AWS_CACHE_BUCKET }},name=miden-node-${{ steps.cache-key.outputs.cache_key }},mode=max
