name: Docker Build Check

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  docker-build:
    strategy:
      matrix:
        component: [node, faucet]
    runs-on: ubuntu-latest
    name: Build ${{ matrix.component }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          cache-binary: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          file: ./bin/${{ matrix.component }}/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
