# Runs the CI

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  rustfmt:
    name: rustfmt nightly on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install minimal Rust with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true
      - name: Install cargo make
        run: cargo install cargo-make
      - name: cargo make - format
        run: cargo make format

  clippy:
    name: clippy stable on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install minimal Rust with clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
          override: true
      - name: Install cargo make
        run: cargo install cargo-make
      - name: cargo make - clippy
        run: cargo make clippy

  doc:
    name: doc stable on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - name: Install cargo make
        run: cargo install cargo-make
      - name: cargo make - format
        run: cargo make doc

  test:
    name: test stable on ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - name: Install cargo make
        run: cargo install cargo-make
      - name: cargo make - format
        run: cargo make test

