name: Publish Crates Dry Run

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cargo Publish Dry Run
        shell: bash
        run: cargo +nightly -Z package-workspace publish --workspace --dry-run
