name: testnet deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
        
permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    name: Deploy to testnet
    uses: ./.github/workflows/deploy_workflow.yml
    with:
      branch: main
      features: testing
    secrets:
      account_id: "${{ secrets.MIDEN_DEV_ACCOUNT_ID }}"
      instance_id: "${{ secrets.TESTNET_INSTANCE_ID }}"
