on:
  push:
    branches:
      - next
  workflow_dispatch:
        
permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    name: Deploy devnet
    # Our devnet instance is arm based.
    runs-on:
      labels: ubuntu22-arm-4core

    # Required for devnet instance access.
    env:
      account-id: "${{ secrets.MIDEN_DEV_ACCOUNT_ID }}"
      instance-id: "${{ secrets.DEVNET_INSTANCE_ID }}"

    steps:
      - uses: actions/checkout@main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::${{ env.account-id }}:role/midendev-GithubActionsRole
          role-session-name: GithubActionsSession

      - name: ssm basic echo
        uses: ./.github/actions/ssm-send-command
        with:
          instance-id: ${{ env.instance-id }}
          command: "echo hello there"

      - name: ssm failure
        uses: ./.github/actions/ssm-send-command
        with:
          instance-id: ${{ env.instance-id }}
          command: "exit 511"
