name: testnet deploy

on:
  push:
    branches:
      - next
  workflow_dispatch:
        
permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    name: Deploy to devnet tf
    uses: ./.github/workflows/deploy_workflow-tf.yml
    with:
      build_prefix: --branch next
    secrets:
      account_id: "${{ secrets.MIDEN_DEV_ACCOUNT_ID }}"
      instance_id: "i-06f7e77fdabe347eb"
