on:
  workflow_call:
    inputs:      
      target:
        type: string
        default: "devnet"
      tag:
        type: string
        default: "next"
    secrets:
      account_id:
        required: true
      instance_id:
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  deploy_tff:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::${{ secrets.account_id }}:role/midendev-GithubActionsRole
          role-session-name: GithubActionsSession

      - name: Determine architecture
        run: |
          ARCHITECTURE=$(uname -m)
          if [[ "$ARCHITECTURE" =~ ^x86 ]]; then
            echo "package_postfix=amd64.dev" >> $GITHUB_ENV
          else
            echo "package_postfix=arm64.dev" >> $GITHUB_ENV
          fi

      - name: Package install testnet
        id: package_install_testnet
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ secrets.instance_id }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
                "sudo rm -f miden-*",                
                "sudo systemctl stop miden-node",
                "sudo systemctl stop miden-faucet",
                "sudo apt remove miden-node miden-faucet -y",
                "wget https://github.com/0xPolygonMiden/miden-node/releases/download/${{ inputs.tag }}/miden-faucet-${{ inputs.tag }}-${{ env.package_postfix }}",
                "wget https://github.com/0xPolygonMiden/miden-node/releases/download/${{ inputs.tag }}/miden-node-${{ inputs.tag }}-${{ env.package_postfix }}",
                "dpkg -i miden-node-${{ inputs.tag }}-${{ env.package_postfix }}",
                "dpkg -i miden-faucet-${{ inputs.tag }}-${{ env.package_postfix }}"
              ]}' \
            --output text \
            --query "Command.CommandId")
          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT
        if: ${{ inputs.target }} == "testnet"

      - name: Poll command status and retrieve live logs from testnet install
        run: |
          while true; do
            STATUS=$(aws ssm list-command-invocations \
                --command-id ${{ steps.package_install_testnet.outputs.command_id }} \
                --details \
                --query "CommandInvocations[0].Status" \
                --output text)
            echo "Command Status: $STATUS"
            
            OUTPUT=$(aws ssm list-command-invocations \
                --command-id ${{ steps.package_install_testnet.outputs.command_id }} \
                --details \
                --query "CommandInvocations[0].CommandPlugins[0].Output" \
                --output text)
            echo "Command Output: $OUTPUT"
            
            if [ "$STATUS" == "Success" ]; then
              echo "Command completed successfully."
              break
            elif [ "$STATUS" == "Failed" ] || [ "$STATUS" == "Cancelled" ]; then
              echo "Command failed with status: $STATUS"
              exit 1
            else
              sleep 10
            fi
          done
        if: ${{ inputs.target }} == "testnet"

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: devnet_package
        if: ${{ inputs.target }} == "devnet"

      - name: Package install devnet
        id: package_install_devnet
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ secrets.instance_id }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
                "sudo rm -f miden-*",                
                "sudo systemctl stop miden-node",
                "sudo systemctl stop miden-faucet",
                "sudo apt remove miden-node miden-faucet -y",
                "dpkg -i miden-node-${{ inputs.tag }}-${{ env.package_postfix }}",
                "dpkg -i miden-faucet-${{ inputs.tag }}-${{ env.package_postfix }}"
              ]}' \
            --output text \
            --query "Command.CommandId")
          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT
        if: ${{ inputs.target }} == "devnet"

      - name: Poll command status and retrieve live logs from devnet install
        run: |
          while true; do
            STATUS=$(aws ssm list-command-invocations \
                --command-id ${{ steps.package_install_devnet.outputs.command_id }} \
                --details \
                --query "CommandInvocations[0].Status" \
                --output text)
            echo "Command Status: $STATUS"
            
            OUTPUT=$(aws ssm list-command-invocations \
                --command-id ${{ steps.package_install_devnet.outputs.command_id }} \
                --details \
                --query "CommandInvocations[0].CommandPlugins[0].Output" \
                --output text)
            echo "Command Output: $OUTPUT"
            
            if [ "$STATUS" == "Success" ]; then
              echo "Command completed successfully."
              break
            elif [ "$STATUS" == "Failed" ] || [ "$STATUS" == "Cancelled" ]; then
              echo "Command failed with status: $STATUS"
              exit 1
            else
              sleep 10
            fi
          done
        if: ${{ inputs.target }} == "testnet"
      

      - name: Configure environment
        id: configure_environment
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ secrets.instance_id }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
                "sleep 10",
                "sudo chown -R miden /opt/miden",
                "sudo /usr/bin/miden-node init -c /etc/miden/miden-node.toml -g /opt/miden/miden-node/genesis.toml",                
                "sudo /usr/bin/miden-node make-genesis -i /opt/miden/miden-node/genesis.toml -o /opt/miden/miden-node/genesis.dat",
                "sudo /usr/bin/miden-faucet init -c /opt/miden/miden-faucet/miden-faucet.toml"                
              ]}' \
            --output text \
            --query "Command.CommandId")
          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT

      - name: Check configure environment command status and retrieve output
        run: |
            while true; do
              STATUS=$(aws ssm list-command-invocations \
                  --command-id ${{ steps.configure_environment.outputs.command_id }} \
                  --details \
                  --query "CommandInvocations[0].Status" \
                  --output text)
              echo "Command Status: $STATUS"
              
              OUTPUT=$(aws ssm list-command-invocations \
                  --command-id ${{ steps.configure_environment.outputs.command_id }} \
                  --details \
                  --query "CommandInvocations[0].CommandPlugins[0].Output" \
                  --output text)
              echo "Command Output: $OUTPUT"
              
              if [ "$STATUS" == "Success" ]; then
                echo "Command completed successfully."
                break
              elif [ "$STATUS" == "Failed" ] || [ "$STATUS" == "Cancelled" ]; then
                echo "Command failed with status: $STATUS"
                exit 1
              else
                sleep 10
              fi
            done


      - name: Start miden node service
        id: start_miden_service
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ secrets.instance_id }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
                "sudo systemctl daemon-reload",
                "sudo systemctl start miden-node"                
              ]}' \
            --output text \
            --query "Command.CommandId")
          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT

      - name: Check Start services command status and retrieve output
        run: |
          while true; do
            STATUS=$(aws ssm list-command-invocations \
                --command-id ${{ steps.start_miden_service.outputs.command_id }} \
                --details \
                --query "CommandInvocations[0].Status" \
                --output text)
            echo "Command Status: $STATUS"
            
            OUTPUT=$(aws ssm list-command-invocations \
                --command-id ${{ steps.start_miden_service.outputs.command_id }} \
                --details \
                --query "CommandInvocations[0].CommandPlugins[0].Output" \
                --output text)
            echo "Command Output: $OUTPUT"
            
            if [ "$STATUS" == "Success" ]; then
              echo "Command completed successfully."
              break
            elif [ "$STATUS" == "Failed" ] || [ "$STATUS" == "Cancelled" ]; then
              echo "Command failed with status: $STATUS"
              exit 1
            else
              sleep 10
            fi
          done

      - name: Start miden faucet service
        id: start_miden_faucet_service
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ secrets.instance_id }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
                "sudo systemctl daemon-reload",
                "sudo systemctl start miden-faucet"
              ]}' \
            --output text \
            --query "Command.CommandId")
          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT

      - name: Check Start services command status and retrieve output
        run: |
          while true; do
            STATUS=$(aws ssm list-command-invocations \
                --command-id ${{ steps.start_miden_faucet_service.outputs.command_id }} \
                --details \
                --query "CommandInvocations[0].Status" \
                --output text)
            echo "Command Status: $STATUS"
            
            OUTPUT=$(aws ssm list-command-invocations \
                --command-id ${{ steps.start_miden_faucet_service.outputs.command_id }} \
                --details \
                --query "CommandInvocations[0].CommandPlugins[0].Output" \
                --output text)
            echo "Command Output: $OUTPUT"
            
            if [ "$STATUS" == "Success" ]; then
              echo "Command completed successfully."
              break
            elif [ "$STATUS" == "Failed" ] || [ "$STATUS" == "Cancelled" ]; then
              echo "Command failed with status: $STATUS"
              exit 1
            else
              sleep 10
            fi
          done
