name: testnet deploy

on:
  release:
    types: [created]
  workflow_dispatch:
        
permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    name: Deploy to testnet
    uses: ./.github/workflows/deploy_workflow.yml
    with:
      build_prefix: "--tag ${{ github.ref_name }}"
    secrets:
      account_id: "${{ secrets.MIDEN_DEV_ACCOUNT_ID }}"
      instance_id: "${{ secrets.TESTNET_INSTANCE_ID }}"
