# Runs documentation related jobs.

name: doc

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

# Limits workflow concurrency to only the latest commit in the PR.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  doc:
    name: doc stable on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build docs
        run: |
          rustup update --no-self-update stable
          make doc
