# Runs documentation related jobs.

name: doc

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  doc:
    name: doc stable on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - name: Doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args:
      - name: Check docs
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: -D warnings
        with:
          command: doc
          args: --verbose --keep-going ${{matrix.args}}
