name: Integration

on:
  push:
    branches:
      - main

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t miden-node-image .

    - name: Run Docker image
      run: docker run -d --name miden-node -p 57291:57291 miden-node-image

    - name: Run Integration tests
      run: ./scripts/run-integration-tests.sh
