
# Runs changelog related jobs.
# CI job heavily inspired by: https://github.com/tarides/changelog-check-action

name: auto-close

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  auto-close:
    runs-on: ubuntu-latest
    steps:
      - name: Log stuff
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          linked_issue_id="$( gh api graphql -f query='
          query($pr:ID!) {
            node(id: $pr) {
              ... on PullRequest {
                closingIssuesReferences(first:1, userLinkedOnly:false) {
                  totalCount
                  nodes { 
                    id 
                  }
                }
              }
            }
          }' -f pr=${{ github.event.pull_request.node_id }} --jq '.data.node.closingIssuesReferences')"
          echo "ISSUE ID:"
          echo "$linked_issue_id"
