# Runs linting related jobs.

name: lint

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

# Limits workflow concurrency to only the latest commit in the PR.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Rustup
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}
      - name: Fmt
        run: make format-check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Rustup
        run: |
          rustup update --no-self-update
          rustup component add clippy
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}
      - name: Clippy
        run: make clippy

  doc:
    name: doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Rustup
        run: rustup update --no-self-update
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}
      - name: Build docs
        run: make doc

  version:
    name: rust version consistency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          profile: minimal
          override: true
      - name: check rust versions
        run: ./scripts/check-rust-version.sh

  proto:
    name: proto check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Rustup
        run: rustup update --no-self-update
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}
      - name: Rebuild protos
        run: BUILD_PROTO=1 cargo check -p miden-node-rpc -p miden-rpc-proto
      - name: Diff check
        run: git diff --exit-code
