# Runs linting related jobs.

name: lint

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

# Limits workflow concurrency to only the latest commit in the PR.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Rustup
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}
      - name: Fmt
        run: make format-check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Rustup
        run: |
          rustup update --no-self-update
          rustup component add clippy
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}
      - name: Clippy
        run: make clippy

  toml:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli
      - run: make toml-check

  workspace-lints:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-workspace-lints
      - run: |
          make workspace-check

  doc:
    name: doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Rustup
        run: rustup update --no-self-update
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}
      - name: Build docs
        run: make doc

  unused_deps:
    name: check for unused dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: machete
        uses: bnjbvr/cargo-machete@main

  proto:
    name: proto check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Rustup
        run: rustup update --no-self-update
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}
      - name: Rebuild protos
        run: BUILD_PROTO=1 cargo check -p miden-node-proto --features=rpc-client
      - name: Diff check
        run: git diff --exit-code
