# Runs linting related jobs.

name: lint

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  version:
    name: check rust version consistency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          profile: minimal
          override: true
      - name: check rust versions
        run: ./scripts/check-rust-version.sh

  rustfmt:
    name: rustfmt check nightly on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Rustfmt
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add rustfmt
          make format-check

  clippy:
    name: clippy stable on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install minimal Rust with clippy
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add clippy
          make clippy

  proto:
    name: proto check
    runs-on: ubuntu-latest
    steps:
      - name: Update rust toolchain
        uses: actions/checkout@main
        run: rustup update --no-self-update
      - name: Rebuild protos
        run: BUILD_PROTO=1 cargo check -p miden-node-rpc -p miden-rpc-proto
      - name: Diff check
        run: git diff --quiet
