# Runs linting related jobs.

name: lint

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

# Limits workflow concurrency to only the latest commit in the PR.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  rustfmt:
    name: rustfmt check nightly on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Rustfmt
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add rustfmt
          make format-check

  clippy:
    name: clippy stable on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install minimal Rust with clippy
        run: |
          rustup update --no-self-update nightly
          rustup +nightly component add clippy
          make clippy

  doc:
    name: doc stable on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build docs
        run: |
          rustup update --no-self-update
          make doc

  version:
    name: check rust version consistency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          profile: minimal
          override: true
      - name: check rust versions
        run: ./scripts/check-rust-version.sh

  proto:
    name: proto check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Update rust toolchain
        run: rustup update --no-self-update
      - name: Rebuild protos
        run: BUILD_PROTO=1 cargo check -p miden-node-rpc -p miden-rpc-proto
      - name: Diff check
        run: git diff --exit-code
