name: Publish All Debian Packages

on:
  release:
    types: [prereleased, released]

  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (E.G. v0.10.0-rc.1, v0.10.0). Corresponding git tag must already exist."
        required: true
        type: string

env:
  version: ${{ inputs.version || github.ref_name }}

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    name: Publish Prover ${{ matrix.arch }} Debian
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on:
      labels: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Build and Publish Node
        uses: ./.github/actions/debian
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitref: ${{ env.version }}
          service: miden-node
          service_short: node
          bin: miden-node
          arch: ${{ matrix.arch }}

      - name: Build and Publish Faucet
        uses: ./.github/actions/debian
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitref: ${{ env.version }}
          service: miden-faucet
          service_short: faucet
          bin: miden-faucet
          arch: ${{ matrix.arch }}

      - name: Build and Publish Prover
        uses: ./.github/actions/debian
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitref: ${{ env.version }}
          service: miden-prover
          service_short: prover
          bin: miden-proving-service
          arch: ${{ matrix.arch }}

      - name: Build and Publish Prover Proxy
        uses: ./.github/actions/debian
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitref: ${{ env.version }}
          service: miden-prover-proxy
          service_short: prover-proxy
          bin: miden-proving-service
          arch: ${{ matrix.arch }}
