name: Publish Prover Debian Package

on:
  release:
    types: [prereleased, released]

  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (E.G. v0.10.0-rc.1, v0.10.0). Corresponding git tag must already exist."
        required: true
        type: string
  # TODO: delete trigger
  pull_request:
    types: [opened, reopened, synchronize]

env:
  version: ${{ inputs.version || github.ref_name }}

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    name: Publish Prover ${{ matrix.arch }} Debian
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on:
      labels: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: ls
        run: |
          ls
          ls .github/
          ls .github/actions/
          ls .github/actions/debian

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          # Only update the cache on push onto the next branch. This strikes a nice balance between
          # cache hits and cache evictions (github has a 10GB cache limit).
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}

      - name: Rust update
        run: |
          rustup update --no-self-update

      - name: Build and Publish Packages
        uses: ./.github/actions/debian
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitref: ${{ env.version }}
          service: miden-prover
          bin: miden-proving-service
          arch: ${{ matrix.arch }}
