name: Publish Proving Service Debian Packages

run-name: Release packaging for ${{ inputs.version || github.ref }}

on:
  release:
    types: [released, prereleased]

  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (E.G. v0.10.0-rc.1, v0.10.0). Corresponding git tag must already exist."
        required: true
        type: string

env:
  version: ${{ inputs.version || github.ref_name }}

permissions:
  id-token: write
  contents: write

jobs:
  package:
    name: ${{ inputs.version }} for ${{ matrix.arch }}
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on:
      labels: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          ref: ${{ env.version}}

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          # Only update the cache on push onto the next branch. This strikes a nice balance between
          # cache hits and cache evictions (github has a 10GB cache limit).
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}

      - name: Rust update
        run: |
          rustup update --no-self-update

      - name: Build packages
        uses: ./.github/actions/debian/proving_service.yml
        with:
          gitref: ${{ env.version }}

      - name: Package names
        run: |
          echo "prover-package=miden-prover-${{ env.version }}-${{ matrix.arch }}.deb" >> $GITHUB_ENV
          echo "prover-proxy-package=miden-prover-proxy-${{ env.version }}-${{ matrix.arch }}.deb" >> $GITHUB_ENV

      - name: Rename package files
        run: |
          mv miden-prover.deb ${{ env.prover-package }}
          mv miden-prover-proxy.deb ${{ env.prover-proxy-package }}

      - name: shasum packages
        run: |
          sha256sum ${{ env.prover-package }} > ${{ env.prover-package }}.checksum
          sha256sum ${{ env.prover-proxy-package }} > ${{ env.prover-proxy-package }}.checksum

      - name: Publish packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ env.version }} \
            ${{ env.prover-package }} \
            ${{ env.prover-package }}.checksum \
            ${{ env.prover-proxy-package }} \
            ${{ env.prover-proxy-package }}.checksum \
            --clobber
