name: Publish Node and Faucet Debian Packages

on:
  release:
    types: [prereleased, released]

  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (E.G. v0.10.0-rc.1, v0.10.0). Corresponding git tag must already exist."
        required: true
        type: string

env:
  version: ${{ inputs.version || github.ref_name }}
  registry: ghcr.io

permissions:
  id-token: write
  contents: write
  packages: write
  attestations: write

jobs:
  publish:
    name: Publish ${{ inputs.version }} Docker
    strategy:
      matrix:
        component: [node, faucet]
    runs-on:
      labels: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          ref: ${{ env.version}}
          fetch-depth: 0

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          file: ./bin/${{ matrix.component }}/Dockerfile
          tags: ${{ env.registry }}/0xmiden/miden-${{ matrix.component }}:${{ env.version }}
