name: Publish Debian Package

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Name of service to publish"
        required: true
        type: choice
        options:
          - miden-node
          - miden-faucet
          - miden-prover
          - miden-prover-proxy
      service_short:
        required: true
        description: The short form service to build the packages for.
        type: choice
        options:
          - node
          - faucet
          - prover
          - prover-proxy
      bin:
        description: "Name of the binary to publish"
        required: true
        type: choice
        options:
          - miden-node
          - miden-faucet
          - miden-proving-service
      version:
        description: "Version to release (E.G. v0.10.0-rc.1, v0.10.0). Corresponding git tag must already exist."
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    name: Publish Prover ${{ matrix.arch }} Debian
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on:
      labels: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Build and Publish Packages
        uses: ./.github/actions/debian
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitref: ${{ inputs.version }}
          service: ${{ inputs.service }}
          service_short: ${{ inputs.service_short }}
          bin: ${{ inputs.bin }}
          arch: ${{ matrix.arch }}
