name: Release-plz (dry-run)

permissions:
  contents: read

on:
  push:
    branches: [main, next]

jobs:
  release-plz-dry-run-release:
    name: Release-plz dry-run
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == '0xMiden' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Rust toolchain
        run: |
          rustup update --no-self-update
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
