# Runs testing related jobs.

name: test

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

# Limits workflow concurrency to only the latest commit in the PR.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: test ${{matrix.toolchain}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
        os: [ubuntu]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@main
      - uses: taiki-e/install-action@nextest 
      - name: Perform tests
        run: |
          rustup update --no-self-update ${{matrix.toolchain}} 
          make test
