name: Beta toolchain

on:
  schedule:
    - cron: "0 6 * * *" # Everyday at 06:00am UTC

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'next'
      - name: Rustup
        run: rustup install beta && rustup default beta
      - uses: taiki-e/install-action@nextest 
      - name: Run tests
        run: make test
