# Runs testing related jobs.

name: test

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  unit-and-integration:
    name: unit and integration tests stable on ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - uses: davidB/rust-cargo-make@v1
      - name: cargo make - test
        run: cargo make test-default

  end-to-end:
    name: end-to-end tests stable on ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - uses: davidB/rust-cargo-make@v1
      - name: cargo make - docker-build-node
        run: cargo make docker-build-node
      - name: cargo make - docker-run-node
        run: cargo make docker-run-node
      - name: cargo install - miden-client
        run: cargo install miden-client --features concurrent,testing
      - name: cargo make - test-end-to-end
        run: cargo make test-end-to-end
