# Runs unit-testing related jobs.

name: unit

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: test stable on ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - name: Install cargo make
        run: cargo install cargo-make
      - name: cargo make - format
        run: cargo make test
